#!/bin/sh
#
# Fuzzy Finder Dynamic GUI Menu
#
# Dependencies: fzf & tail

#---------------------------------------
#               Config
#---------------------------------------

FLAG_CLASS=-c #st
# FLAG_CLASS=-class  #xterm
# FLAG_CLASS=--class #termite

FLAG_GEOMETRY=-g #st
# FLAG_GEOMETRY=-geometry #xterm

WIDTH=40
HEIGHT=10
OFFSET_X=450
OFFSET_Y=200

export FZF_DEFAULT_OPTS="\
   --cycle
   --print-query
   --no-multi
   --reverse --border bottom --no-info --no-color --header '' --margin 0%,0%
   --bind \;:accept
   --bind esc:cancel
   --bind tab:down
   --bind btab:up
"

#---------------------------------------
#               Script
#---------------------------------------

ARGS=/tmp/AMENU_ARGS
OUTPUT=/tmp/AMENU_OUTPUT

scan_args() {
   while IFS= read -r line; do echo "$line"; done
   [ -n "$line" ] && echo "$line"
}
show() { while IFS= read -r line; do echo "$line"; done < $OUTPUT; }
run_menu() {
   scan_args > $ARGS
   prompt
   show
}
run_app() { read -r PROGRAM < $OUTPUT && $PROGRAM > /dev/null 2>&1 & }
prompt() {
   GEOMETRY=$WIDTH"x"$HEIGHT+$OFFSET_X+$OFFSET_Y

   : > $OUTPUT
   $TERMINAL \
      $FLAG_CLASS amenu \
      $FLAG_GEOMETRY $GEOMETRY \
      -e "$SHELL" -c "fzf $PROMPT < $ARGS | tail -1 > $OUTPUT" 2> /dev/null
   read -r CHOICE < $OUTPUT
   [ -z "$CHOICE" ] && exit 1
}
scan_apps() {
   for program in /usr/bin/* /usr/local/bin/*; do
      echo "${program##*/}"
   done > $ARGS
}
run_launcher() {
   scan_apps
   prompt
   run_app
}
main() {
   case $1 in
      -l) run_launcher ;;
      -p) PROMPT="--header $2" && run_menu ;;
      *) run_menu ;;
   esac
}
main "$@"
