#!/bin/sh
#
# Emulates Dmenu behavior using default terminal
# Note: Use your window manager to make the class "scratchpad" floating
#
# Dependencies: fzf

#---------------------------------------
#               Config
#---------------------------------------

WIDTH=40
HEIGHT=10
OFFSET_X=450
OFFSET_Y=200

# SCRATCHPAD="$TERMINAL -c scratchpad -g "$WIDTH"x$HEIGHT+$OFFSET_X+$OFFSET_Y -e $SHELL -c"

#---------------------------------------
#               Script
#---------------------------------------

# APPS=/tmp/TMENU_APPS
ARGS=/tmp/TMENU_ARGS
OUTPUT=/tmp/TMENU_OUTPUT
PROMPT=

scan_args() {
   while IFS= read -r line; do
      echo "$line"
   done > $ARGS
   [ -n "$line" ] && echo "$line" > $ARGS
   # cat > $ARGS
}

print() {
   while IFS= read -r line; do
      echo "$line"
   done < $OUTPUT
   # cat $OUTPUT
}

run_menu() {
   scan_args
   prompt
   print
}

run_app() {
   read -r PROGRAM < $OUTPUT
   $PROGRAM &
}

prompt() {
   $TERMINAL -c scratchpad -g "$WIDTH"x$HEIGHT+$OFFSET_X+$OFFSET_Y \
      "$SHELL" -c "fzf $PROMPT < $ARGS > $OUTPUT" || exit 1
   # -e "$SHELL" -c "fzf $PROMPT < $ARGS > $OUTPUT" 2>/dev/null || exit 1
   # $SCRATCHPAD "fzf $PROMPT < $ARGS > $OUTPUT" 2> /dev/null || exit 1

   # if [ "$1" = -l ]; then
   #    INPUT=$APPS
   # else
   #    INPUT=$ARGS
   # fi
   # $TERMINAL -c scratchpad -g "$WIDTH"x$HEIGHT+$OFFSET_X+$OFFSET_Y \
   #    -e "$SHELL" -c "fzf $PROMPT < $ARGS > $OUTPUT" 2> /dev/null || exit 1
}

scan_apps() {
   for program in /usr/bin/* /usr/local/bin/*; do
      echo "${program##*/}"
   done > $ARGS
}

run_launcher() {
   scan_apps
   prompt
   run_app
}

main() {
   : > $ARGS
   case $1 in
      -l)
         run_launcher
         ;;
      -p)
         PROMPT="--header $2"
         run_menu
         ;;
      *)
         run_menu
         ;;
   esac
}
main "$@"
